site_name: Tools for Big Data Analytics - Group 3
theme:
  name: material
  palette:
    primary: blue
    accent: light blue

nav:
  - Home: README.md
  - Frontend:
      - Placeholder/Overview: frontend/ui.md
      
  - Backend:
      - Placeholder/Overview: backend/api.md
  - Documentation overview: overview.md
  - Architecture: architecture.md
  - Sprint Summaries
      - Placeholder/Overview: sprint-summaries/sprint1.md
      - Placeholder/Overview: sprint-summaries/sprint1.md

site_url: https://tbda-classes.github.io/2025G3/
