site_name: Tools for Big Data Analytics - Group 3
theme:
  name: material
  palette:
    primary: blue
    accent: light blue

nav:
  - Home: README.md
  - Documentation overview: overview.md
  - Architecture: architecture.md
  - Sprint Summaries:
      - Sprint 1 Summary: sprint-summaries/sprint1.md
      - Sprint 2 Summary: sprint-summaries/sprint2.md
  - Frontend:
      - Placeholder/Overview: frontend/ui.md
  - Backend:
      - Placeholder/Overview: backend/api.md
  


site_url: https://tbda-classes.github.io/2025G3/
